ITEM_PRIMARY = 0;
ITEM_MELEE = 1;
ITEM_PARTS = 2;
ITEM_ARMOR = 3;

SHOT_ARC = 0;
SHOT_AUTO = 1;
SHOT_SPREAD = 2;
SHOT_LASER = 3;

ATTR_MAX_HP = 0;
ATTR_MAX_EN = 1;
ATTR_MELEE_POWER = 2;
ATTR_RANGE_POWER = 3;
ATTR_ARMOR = 4;
ATTR_SPEED = 5;

IS_RATIO = true;
IS_FIXED = false;