ITEM_WEAPON = 0;
ITEM_PARTS = 1;
ITEM_ARMOR = 2;

WEAPON_ARC = 0;
WEAPON_AUTO = 1;
WEAPON_SPREAD = 2;
WEAPON_LASER = 3;
WEAPON_MELEE = 4;

ATTR_MAX_HP = 0;
ATTR_MAX_EN = 1;
ATTR_MELEE_POWER = 2;
ATTR_RANGE_POWER = 3;
ATTR_ARMOR = 4;
ATTR_SPEED = 5;

IS_RATIO = true;
IS_FIXED = false;